# Generated by Django 5.1.4 on 2025-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_fname_remove_order_lname_orderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fname',
            field=models.CharField(default='Ral', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(default='Kaja', max_length=150),
            preserve_default=False,
        ),
    ]
