# Generated by Django 5.1.4 on 2025-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_fname_order_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprofile',
            name='fname',
            field=models.CharField(default='Amit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderprofile',
            name='lname',
            field=models.CharField(default='Haldar', max_length=150),
            preserve_default=False,
        ),
    ]
