# Generated by Django 5.1.4 on 2025-02-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderprofile_fname_orderprofile_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='orderprofile',
            name='lname',
        ),
    ]
