# Generated by Django 5.1.4 on 2025-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_orderprofile_email_remove_orderprofile_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
