# Generated by Django 5.1.3 on 2025-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_rating_user_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
