# Generated by Django 5.1.3 on 2025-02-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_pics', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.review')),
            ],
        ),
    ]
